[project]
name = "leapfrog-compare"
version = "0.0.7"
description = "Compare Spectrum extract output with leapfrog-goals model output"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1",
    "pandas>=2.0",
    "numpy>=1.24",
    "shiny>=1.2",
    "plotly>=5.0",
    "avenir-spectrum-common>=0.1.23",
    "avenir-spectrum-import-pjnz>=0.1.16",
    "leapfrog-goals>=1.0.2",
    "shinywidgets>=0.8.1",
    "leapfrog-py>=1.0.15",
]

# Uncomment and set the path to use local version of leapfrog-goals when developing
#[tool.uv.sources]
#leapfrog-goals = { path = "../leapfrog/goals", editable = true }
#leapfrog-py = { path = "../leapfrog/leapfrog-py", editable = true }
#avenir-spectrum-common = { path = "C:\\Users\\Test\\projects\\SpectrumEngine\\SpectrumCommon", editable = true }
#avenir-spectrum-import-pjnz = { path = "C:\\Users\\Test\\projects\\SpectrumEngine\\Tools\\ImportPJNZ", editable = true }

[build-system]
requires = ["uv_build>=0.11.1,<0.12"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[project.scripts]
app = "shiny:run_app"
